# Generated by Django 3.2.4 on 2021-06-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inicio_sesion',
            fields=[
                ('correo', models.IntegerField(primary_key=True, serialize=False, verbose_name='correo')),
                ('contraseña', models.CharField(max_length=20, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido')),
                ('correo_electronico', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='correo_electronico')),
                ('telefono', models.IntegerField(max_length=10, verbose_name='telefono')),
                ('fecha_nacimiento', models.CharField(max_length=10, verbose_name='fecha_nacimiento')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('region', models.CharField(max_length=15, verbose_name='region')),
                ('genero', models.CharField(max_length=9, verbose_name='genero')),
                ('inicio_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.inicio_sesion')),
            ],
        ),
    ]
